language: python
sudo: False
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.8
      env: TOXENV=py28
    - python: 2.9
      env: TOXENV=py29
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
install:
  - pip install tox
  - pip install -r requirements.txt
script:
  - tox -e $TOXENV
